language: objective-c
osx_image: xcode7.2
before_script: wget https://raw.githubusercontent.com/uraimo/SwiftyGPIO/master/Sources/SwiftyGPIO.swift -P Sources/
script: files=$(find Sources -regex '.*[^/]swift') && xcrun -sdk macosx swiftc $files
